-- ============================================================
-- Onboarding cascade: ICP profile region metadata
-- Projects:
--   - selltonai: ICP UI and campaign creation can prefill from onboarding ICPs
--   - selltonai-modal: V2 cascade creates ICP profiles from approved onboarding output
-- App changes required together:
--   - V2CascadeService should populate these fields when creating ICP rows.
-- ============================================================

ALTER TABLE public.icp_profiles
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS line_of_business TEXT,
  ADD COLUMN IF NOT EXISTS auto_generated_from_onboarding BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS onboarding_research_id UUID REFERENCES public.onboarding_research(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_icp_profiles_region
  ON public.icp_profiles(organization_id, region)
  WHERE region IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_icp_profiles_lob
  ON public.icp_profiles(organization_id, line_of_business)
  WHERE line_of_business IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_icp_profiles_onboarding_generated
  ON public.icp_profiles(organization_id, auto_generated_from_onboarding)
  WHERE auto_generated_from_onboarding = TRUE;

COMMENT ON COLUMN public.icp_profiles.region IS 'Region tag for onboarding-generated or manually regionalized ICP profiles.';
COMMENT ON COLUMN public.icp_profiles.line_of_business IS 'Line-of-business tag for enterprise/multi-stakeholder ICP profiles.';
COMMENT ON COLUMN public.icp_profiles.auto_generated_from_onboarding IS 'True when the profile was generated by V2 onboarding cascade.';
COMMENT ON COLUMN public.icp_profiles.onboarding_research_id IS 'Optional link back to onboarding_research source row.';
